---
name: baetobe
description: A dating app for working professionals
publish_to: none
version: 1.0.0+66
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  firebase_remote_config: ^2.0.0
  firebase_messaging: ^11.2.6
  dio: ^4.0.4
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.0
  intl: ^0.17.0
  google_fonts: ^2.2.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  auto_route: ^3.2.2
  getwidget: ^2.0.4
  url_launcher: ^6.0.18
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.3
  flutter_secure_storage: ^5.0.2
  flutter_facebook_auth: ^4.0.1
  styled_widget: ^0.4.0+3
  syncfusion_flutter_datepicker: ^19.4.47
  geocoding: ^2.0.2
  location: ^4.3.0
  flutter_typeahead: ^3.2.4
  connectivity_plus: ^2.2.0
  cached_network_image: ^3.2.0
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.4+5
  camera: ^0.9.4+9
  file_picker: ^4.3.3
  flutter_local_notifications: ^9.2.0
  webview_flutter: ^3.0.0
  pull_to_refresh: ^2.0.0
  alice: ^0.2.5
  flutter_chat_ui: ^1.5.5
  action_cable: ^1.2.0
  uuid: ^3.0.5
  flutter_slidable: ^1.2.0
  debug_friend: ^0.4.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  firebase_in_app_messaging: ^0.6.0+7
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.2
  http_mock_adapter: ^0.3.2
  mockito: ^5.0.17
  auto_route_generator: ^3.2.1
  freezed: ^1.1.1
  json_serializable: ^6.1.4
flutter_icons:
  android: ture
  ios: true
  image_path_ios: assets/logo_with_bg.jpg
  image_path: assets/logo.png
  adaptive_icon_background: '#ffffff'
flutter_native_splash:
  color: '#fefefe'
  image: assets/logo.png
  android: true
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/launcher/
  - assets/splash_logo/
  fonts:
  - family: BTBCustomIcons
    fonts:
    - asset: assets/fonts/BTBCustomIcons.ttf
